version: 1.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{appveyor_build_version}'
  assembly_file_version: '{appveyor_build_version}'
  assembly_informational_version: '{appveyor_build_version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{appveyor_build_version}'
  package_version: '{appveyor_build_version}'
  assembly_version: '{appveyor_build_version}'
  file_version: '{appveyor_build_version}'
  informational_version: '{appveyor_build_version}'
before_build:
- cmd: dotnet restore src
build:
  verbosity: minimal

build_script:
- ps: .\Build.ps1

artifacts:
    - path: .\artifacts\*

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: lRgjizJgJ+gShbGwlM7Sl+P2NEPJ1drvOCPTbaU0qsa0kxS7E4oA7ylaHgNlJ0T7
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/